### ISSUE TITLE
Change documentation to support use of ENTRYPOINT

### ISSUE THREAD

**Issue by SakuraSound** [ubergarm/sanic-alpine#1]
There is a small issue in calling commands now using this docker image:

```$ docker run --rm -it -v `pwd`:/app -p 8000:8000 ubergarm/sanic-alpine python3 app/server.py```
returns the following error
```/usr/bin/python3: can't open file 'python3': [Errno 2] No such file or directory```

The fix is simple, and I can create the PR. If you remove **python3** from the command, you should get proper output:

```docker run --rm -it -v `pwd`:/app -p 8000:8000 ubergarm/sanic-alpine app/server.py```
will start the server
```
2017-04-05 22:25:19,590: INFO: Goin' Fast @ http://0.0.0.0:8000
2017-04-05 22:25:19,594: INFO: Starting worker [1]
```

**Comment by ubergarm** [comment]
Ooh, great. Sorry just saw this. 

Yes, you're totally right, I didn't update the docs after making a change!
